plugins {
    id 'com.gradle.plugin-publish' version '2.1.1'
    id 'io.freefair.lombok' version '9.5.0'
    id 'org.sonarqube' version '7.3.1.8318'
    id 'java-gradle-plugin'
    id 'maven-publish'
    id 'jacoco'
}

group = 'com.github.akazver.mapstruct'
version = System.getenv("RELEASE_VERSION") ?: "dev"

gradlePlugin {
    website = 'https://github.com/AkaZver'
    vcsUrl = 'https://github.com/AkaZver/mapstruct-plugin'

    plugins {
        mapstruct {
            id = 'com.github.akazver.mapstruct'
            displayName = 'MapStruct Plugin'
            description = 'Automatic MapStruct configuration'
            implementationClass = 'com.github.akazver.gradle.plugins.mapstruct.MapstructPlugin'
            tags.set(['mapstruct', 'mapping', 'lombok', 'spring', 'quarkus', 'camel'])
        }
    }
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    testImplementation 'io.freefair.gradle:lombok-plugin:9.5.0'
    testImplementation 'org.assertj:assertj-core:3.27.7'
    testImplementation 'org.junit.jupiter:junit-jupiter:6.1.2'
    testImplementation 'org.junit.platform:junit-platform-launcher:6.1.2'
    testImplementation 'org.mockito:mockito-core:5.23.0'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.23.0'
}

test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}

java {
    sourceCompatibility = 17
    targetCompatibility = 17
    withSourcesJar()
}

jacocoTestReport {
    dependsOn test

    reports {
        xml.required = true
    }
}

sonarqube {
    properties {
        property "sonar.projectKey", "AkaZver_mapstruct-plugin"
        property "sonar.organization", "aka-zver"
        property "sonar.host.url", "https://sonarcloud.io"
        property "sonar.java.binaries", "build/classes/java/main"
        property "sonar.java.test.binaries", "build/classes/java/test"
    }
}

javadoc {
    options.addStringOption('Xdoclint:none', '-quiet')
}
